//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

public partial class RideklubbenContext : ObjectContext
{
    public const string ConnectionString = "name=RideklubbenContext";
    public const string ContainerName = "RideklubbenContext";

    #region Constructors

    public RideklubbenContext()
        : base(ConnectionString, ContainerName)
    {
        this.ContextOptions.LazyLoadingEnabled = true;
    }

    public RideklubbenContext(string connectionString)
        : base(connectionString, ContainerName)
    {
        this.ContextOptions.LazyLoadingEnabled = true;
    }

    public RideklubbenContext(EntityConnection connection)
        : base(connection, ContainerName)
    {
        this.ContextOptions.LazyLoadingEnabled = true;
    }

    #endregion

    #region ObjectSet Properties

    public ObjectSet<Billede> Billeder
    {
        get { return _billeder  ?? (_billeder = CreateObjectSet<Billede>("Billeder")); }
    }
    private ObjectSet<Billede> _billeder;

    public ObjectSet<Ejerskab> Ejerskaber
    {
        get { return _ejerskaber  ?? (_ejerskaber = CreateObjectSet<Ejerskab>("Ejerskaber")); }
    }
    private ObjectSet<Ejerskab> _ejerskaber;

    public ObjectSet<Hest> Heste
    {
        get { return _heste  ?? (_heste = CreateObjectSet<Hest>("Heste")); }
    }
    private ObjectSet<Hest> _heste;

    public ObjectSet<Rytter> Ryttere
    {
        get { return _ryttere  ?? (_ryttere = CreateObjectSet<Rytter>("Ryttere")); }
    }
    private ObjectSet<Rytter> _ryttere;

    public ObjectSet<Rytter_Ejer> Rytter_Ejere
    {
        get { return _rytter_Ejere  ?? (_rytter_Ejere = CreateObjectSet<Rytter_Ejer>("Rytter_Ejere")); }
    }
    private ObjectSet<Rytter_Ejer> _rytter_Ejere;

    #endregion
}
